name: calc84
description: "An open source graphing calculator that recreates the look and feel of a classic handheld."
publish_to: 'none'
version: 1.2.1+4

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.otf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_channel_ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#16181d"
  adaptive_icon_foreground: assets/icon/app_icon_fg.png
  web:
    generate: true
    image_path: assets/icon/app_icon.png
  windows:
    generate: true
    image_path: assets/icon/app_icon.png
  macos:
    generate: true
    image_path: assets/icon/app_icon.png
  linux:
    generate: true
    image_path: assets/icon/app_icon.png
